server:
  port: 9090
spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:dev_db"
    username: "sa"
    password: "sa"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
    cloud:
      circuitbreaker:
        resilience4j:
          instances:
            agifyService:
              timeout-duration: 5000ms
              failure-rate-threshold: 50
cors:
  originPatterns: http://localhost:3000,http://localhost:9090
external:
  agifyApi:
    url: https://api.agify.io/?name=
logging:
  level:
    root: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: log/application.log




